version: '3'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    ports:
      - 5632:5432
