version: '2'
services:
  ibmmq:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.ibmmq
    image: ibmmq
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_ENABLE_METRICS=true
    ports:
      - 1414:1414
      - 9443:9443
      - 9157:9157